package com.newresources.funkyquest.dto.util;

public enum EventType {
    GAME_STATUS_CHANGED,
    GAME_EDITED,
    GAME_FINISHED,
    GAME_CANCELLED,
    PLAYER_CONNECTED,
    ANSWER_ACCEPTED,
    ANSWER_REJECTED,
    ANSWER_POSTED,
    LOCATION_CHANGED,
    TEAM_CREATED,
    TEAM_CHANGED,
    TEAM_DELETED,
    HINT_REQUESTED,
    BALANCE_RECHARGED
}